### ISSUE TITLE
Unable to edit any tooltip values

### ISSUE THREAD

**Issue by ddbrown30** [illandril/FoundryVTT-token-tooltips#101]
**Describe the bug**
In the Configure Tooltip Values menu, I'm unable to modify any of the values. I can change the permission, gm sees, and show on persistent options but none of the actual tooltip values.

**What steps did you take before experiencing the problem?**
1. Open Configure Tooltip Values menu
2. Attempt to change values on any of the entries

**What did you expect to happen?**
I can change values.

**What happened instead?**
I couldn't change values.

**Screenshots**
![Screenshot 2024-06-01 130454](https://github.com/illandril/FoundryVTT-token-tooltips/assets/9253904/6c3e409c-2ea8-4cc4-8aa0-89ba67694c7b)

**Foundry Versions**
 - Version of this module: 3.9.0
 - Foundry Version: v11.315 (also broken in v12.325 with 4.0.0)
 - System Name and Version: SWADE 3.4.0 and 4.0.0dev
 - Browser Name and Version: Firefox and Chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
None

**Additional context**
Setting export, in case that's helpful
[illandril-token-tooltips_export_123_2024-06-01T20 03 04.525Z.json](https://github.com/user-attachments/files/15523136/illandril-token-tooltips_export_123_2024-06-01T20.03.04.525Z.json)

**Comment by illandril** [comment]
There are two sections of the tooltip settings: "Standard Tooltip Values", and "Custom Tooltip Values".

The standard ones have some extra logic so they work for lots of systems, including some where it isn't a straight single value. These can be enabled or disabled (based on permission settings), but the value cannot be modified.

The custom ones can be fully configured. To add a custom value, click the big "Add" button near the bottom.

**Comment by ddbrown30** [comment]
Ah, okay. I'm assuming there's no way to change the distance calculation then? It doesn't seem to respect the new diagonals setting in v12 and I don't see any way to change it in v11 to do anything other than count grid squares.

**Comment by illandril** [comment]
There are four options for the distance calculator, configurable on the main settings page for the module 

> Specify how the Distance Ruler calculates diagonal distances from for scenes using Square grids. 'Use Grid Measurements' will measure the same way as the Measure Distance tool (ignores elevation). 'Euclidian': The absolute distance (e.g. 5ft square -> 1 diagonal = 7.07ft, 2 diagonals = 14.14ft, etc). 'Equidistant': Diagonals are treated as straights (5ft square -> one diagonal = 5ft, two diagonals = 10ft, etc). 'Alternating': Diagonals are treated as one or two straights alternating (5ft square -> one diagonal = 5ft, two diagonals = 15ft, three diagonals = 20ft, etc)

This setting is separate from the diagonal settings used elsewhere in Foundry (which can vary from system to system exactly how this is specified).

**Comment by ddbrown30** [comment]
Not for me. This screenshot is v11.315 on 3.9.0.

![Screenshot 2024-06-01 174402](https://github.com/illandril/FoundryVTT-token-tooltips/assets/9253904/20d952ad-a503-4847-96d5-d715021ee200)
