### ISSUE TITLE
Add an option to disable tooltips on a per-client basis

### ISSUE THREAD

**Issue by illandril** [illandril/FoundryVTT-token-tooltips#114]
**Is your feature request related to a problem? Please describe.**
From https://github.com/illandril/FoundryVTT-token-tooltips/issues/96#issuecomment-2407535570
> some of my players got annoyed by the tooltips, cause those take a lot of the space on their monitor. One of them even said they had performance issues because of that, but It's hard for me to verify that.

**Describe the solution you'd like**
> So giving them an option to just disable a module activity on their side would really help

**Describe alternatives you've considered**
x

**What system(s) do you want this feature to work with?**
x

**What other modules do you use that you want to ensure work well with this feature?**
x

**Additional context**
x

**Comment by illandril** [comment]
cc: @ilgaran

**Comment by ilgaran** [comment]
Wow, thanks for reacting this fast, really appreciate you!
