### ISSUE TITLE
Spell slots and resources not showing for GMs, regardless of settings

### ISSUE THREAD

**Issue by seacaster** [illandril/FoundryVTT-token-tooltips#16]
Tested in a new world with only this module active. This is the character:
![image](https://user-images.githubusercontent.com/12748616/104827023-a3ccaa00-5827-11eb-8b94-90a5c18499a8.png)
What the GM sees:
![image](https://user-images.githubusercontent.com/12748616/104827040-cc54a400-5827-11eb-8ff0-d7ed7e72ee53.png)
What a non-GM sees:
![image](https://user-images.githubusercontent.com/12748616/104827028-b8a93d80-5827-11eb-82f2-099f2a9239b4.png)
Settings:
![image](https://user-images.githubusercontent.com/12748616/104827048-d7a7cf80-5827-11eb-9365-72ccc136e6a3.png)
Player permissions:
![image](https://user-images.githubusercontent.com/12748616/104827054-e1313780-5827-11eb-9d9e-40b8b93fad20.png)

**Comment by MS-PBS** [comment]
I can confirm I also have this issue. I have the latest version of foundry and DnD 5e.
