### ISSUE TITLE
[Minor Feature Request] Add data attributes movement

### ISSUE THREAD

**Issue by p4535992** [illandril/FoundryVTT-token-tooltips#18]
Add data attributes movement on the tooltip (maybe with a settings so anyone customize the set):
 - Walk
 - Swim
 - Fly
 - Climb
 - Burrow

**Comment by illandril** [comment]
This information is already available in the tooltip, shown for any movement type that is greater than 0 for each token as long as the "Show Movement" setting is enabled.

Make sure you have the latest version of the module (1.4.1), and have the "Show Movement" option checked under the module's settings.

Walk movement is shown next to an icon of a person walking. Swim movement is shown next to an icon of a person swimming. Fly movement is shown next to an icon of a feather. Climb movement is shown next to an icon of a spider. Burrow movement is shown next to an icon of a double down arrow. See [this image](/illandril/FoundryVTT-token-tooltips/blob/master/screenshots/cover.png?raw=true) for examples (giant bat has flight, bulette has burrow, reef shark has swim, everything except the reef shark has walk).
