### ISSUE TITLE
Suggestion: Allow static items to be rearranged

### ISSUE THREAD

**Issue by ckdragons** [illandril/FoundryVTT-token-tooltips#30]
Suggestion: Allow the static items to be rearranged with the custom items. Since I'm using PF1, I like having the 1st column with HP, AC, touch AC, flat-footed AC, and CMD, the 2nd column being saving throws and Perception. Lastly I wanted to have Speed last.

Further, I wasn't able to add the speed as a custom item in the same manner as how the static speed lists any speed types if they exist.

**Comment by illandril** [comment]
For someone playing PF1, if they want AC shown, is it almost guaranteed they will also want Touch AC, Flat-footed AC, and CMD shown as well? If so, I can add those three values to the static AC item for PF1.

What value(s) are you using for Saving Throws? Those are likely useful for many PF1 players, so I'd like to add them to the static list.

Is Perception showing correctly for PF1 in the static items or is that a custom as well? If so, what custom value are you using?

Moving speed after immunities probably would be preferable for most people, so I can also move that in the static item list.

I'm thinking that all of those changes would be quicker and easier than allowing the static item list to be rearranged (and would probably benefit more people), while still getting you the end-result you want.

**Comment by ckdragons** [comment]
This is true. In fact, I was able to add Touch (data.attributes.ac.touch.total), Flat-Footed (data.attributes.ac.flatFooted.total), and CMD (data.attributes.cmd.total) as custom items after HP and AC.

For the Saving Throws, I'm using data.attributes.savingThrows.fort.total, replacing "fort" with "ref' and "will" to list all 3 individually (the savingThrows is case-sensitive).

For Perception, I'm using data.skills.per.mod. Perception in PF1 is somewhat static but it can be modified by certain buffs and conditions.

The issue with Moving speed is I like how you originally have it programmed. It shows all the speeds if they exist on the character.
![image](https://user-images.githubusercontent.com/84493092/121076049-c9346300-c78a-11eb-8ca6-2ac4c9205110.png)
and 
![image](https://user-images.githubusercontent.com/84493092/121076074-d2bdcb00-c78a-11eb-9d32-b88b86c20578.png). You can see how the multiple movements on the 2nd screenshot can change the order of the columns, where as I was hoping to use the same programming but at the end of all items, including custom items. For example: 
![image](https://user-images.githubusercontent.com/84493092/121076269-0e589500-c78b-11eb-96c2-0c9f41149cd4.png) (I had to add data.attributes.speed.land.total, data.attributes.speed.fly.total, and data.attributes.speed.fly.maneuverability to show these movement modes). This last one can't be done because I understand what you're saying about the difficulties of this type of change, it's a nice to have and not something I'd consider "game breaking".

Appreciate your quick response, thank you!

**Comment by illandril** [comment]
I think what I've done will meet your needs, but if you still can't quite get the tooltips set up the way you want please feel free to reopen this issue (or one of the other two issues) and/or open a new issue for any remaining changes you want.

**Comment by ckdragons** [comment]
Thank you. I won't be able to test these new features until I upgrade to 0.8.7. Still on 0.7.1. I want to wait until Foundry gets the bugs worked with another update for upgrading.
