### ISSUE TITLE
List of Icons Available

### ISSUE THREAD

**Issue by ckdragons** [illandril/FoundryVTT-token-tooltips#31]
Is there a list of icons available?

**Comment by illandril** [comment]
Yes (sort of). I've just added this to the README:
> For the custom tooltip values, the icon name is the name of the Font Awesome icon you want to show. You can search for icons [on the Font Awesome website](https://fontawesome.com/icons). Note that not all Font Awesome icons are available (FoundryVTT itself is in control over which icons are available, not this module - this module is just using the icons that are shipped with FoundryVTT).

I'll update the module to include some help text somewhere as well for this, for those who don't check the GitHub page.

**Comment by ckdragons** [comment]
And I read the ReadMe. haha! Completely glossed over that part. Thank you for clarifying.

**Comment by illandril** [comment]
You didn't gloss over it - that part of the readme didn't exist until after you opened this issue. I added it because you asked the question.
