### ISSUE TITLE
Hide from Everyone with GM enabled still hides it from GM

### ISSUE THREAD

**Issue by ckdragons** [illandril/FoundryVTT-token-tooltips#32]
Was the intention to include the GM when the Hide from Everyone permission is set? When I set an item to this permission, and GM is set to active, the item does not appear on the tooltip.

**Comment by illandril** [comment]
Yes, it was intentional - the GM is part of "Everyone".
I can add more permission options though. Do you want visibility for GMs only, or both GMs and Assistant GMs?

**Comment by ckdragons** [comment]
Got it! If you were to expand the permissions, maybe have "Everyone" exclude GM since there is already a toggle for it and have GM include both GMs and Assistant GMs.
