### ISSUE TITLE
Request: Allow for math in the Datakey section. 

### ISSUE THREAD

**Issue by Michael-B-23** [illandril/FoundryVTT-token-tooltips#40]
I'd like to show "Will DC", "Reflex DC" and "Fort DC" as a pop up in PF2E.

Unfortunately, that number is not stored as a data key. Its auto calculated based on off of, for example, "data.saves.reflex.totalModifier" +10.

So if there was a way to do something like
(data.saves.reflex.totalModifier + 10) 
OR
{mod=<data.saves.reflex.totalModifier>; mod+10 }

that would be very helpful. Thank you.

**Comment by illandril** [comment]
This is doubly fixed.

1. For PF2e, if you enable the standard "Saving Throws" row, it will show both the modifier and DC for each saving throw: "Fort +7 (DC 17)"
2. Addition and subtraction are now supported for custom values: `data.saves.reflex.totalModifier + 10`
