### ISSUE TITLE
[FEATURE] - Support for Foundry v9?

### ISSUE THREAD

**Issue by BlackWand1** [illandril/FoundryVTT-token-tooltips#46]
Hi!
Nice module!

Does it have support for Foundry v9 yet?

/Cheers

**Comment by illandril** [comment]
I have not tested Foundry v9 yet, and might not have time to get to it for another week or two.
It's possible it will just work without me needing to make any changes to support v9, so you could try it if you want, I just can't guarantee it will work.

**Comment by BlackWand1** [comment]
Yeah probably. More or less only using "mouse over" and getting data from the data.* properties.

Robert Winbladh
________________________________

**Comment by BlackWand1** [comment]
Looks to be working good.

**Comment by illandril** [comment]
No changes were necessary to support v9.
