### ISSUE TITLE
[FEATURE] Custom Tooltip values in the form X / Y

### ISSUE THREAD

**Issue by alec-hoyland** [illandril/FoundryVTT-token-tooltips#47]
Hi, and great work with this module!

I'm trying to create a custom tooltip for Pathfinder 2 that does the variant [Stamina rule](https://2e.aonprd.com/Rules.aspx?ID=1378).
Basically, I want it to appear like hit points with "[current stamina] / [max stamina]". I know the value and max that I need is `data.attributes.sp.value` and `data.attributes.sp.max` but I don't know how to fill out the 'data key' to make that happen. Is this feature implemented already and if so how do I do it?

Thanks!

![image](https://user-images.githubusercontent.com/30243182/149373163-7a9a0db3-6a37-498e-9fbc-1dc02aecaa4a.png)

**Comment by illandril** [comment]
Setting the Data Key to just `data.attributes.sp` should do it. If that doesn't work, you can re-open this issue and I'll investigate why it isn't working once I have time.

**Comment by alec-hoyland** [comment]
Worked, thanks!
