### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by afalk** [illandril/FoundryVTT-token-tooltips#50]
I would really appreciate the ability to remove entirely or at least edit your base line stats (health, AC, Saves, ETC) esp to put in my custom ones !  Adding new bits or clarifying them with custom pieces adds up fast!  Great tool and super handy -- THANKS in advance!

**Comment by illandril** [comment]
You already can hide them - set "Permission to Show" to "Hide from Everyone"
