### ISSUE TITLE
Tooltip window not displaying with recent foundry update

### ISSUE THREAD

**Issue by bduffy02** [illandril/FoundryVTT-token-tooltips#56]
The tooltip is not displaying. I have updated to the latest version of your mod at the time of this posting. I am currently  using Foundryvtt Version 9 - Build 269. running pathfinder 1e version 0.80.20

**Comment by illandril** [comment]
I cannot reproduce this.

What version of Illandril's Token Tooltips are you using?
What other modules are you using?
What are your Illandri's Token Tooltips settings set to?

**Comment by bduffy02** [comment]
I found a solution. I had to uninstall, delete the file in the user data folder, then reinstall.
