### ISSUE TITLE
Optionally display tooltip only when hotkey is held

### ISSUE THREAD

**Issue by demogordian** [illandril/FoundryVTT-token-tooltips#57]
**Is your feature request related to a problem? Please describe.**
When hovering around a map with more than a few actors (e.g. a larger scale combat), tooltips can be distracting when moving the mouse around icons.

**Describe the solution you'd like**
Add an optional hotkey (e.g. ctrl/alt/shift) that must be held for tooltips to display on hover.  When the hotkey is not used, tooltips are disabled.

**Describe alternatives you've considered**
I originally looked to add custom info to Token Info Icons module (in addition to passive skills), but it seems a bigger change for that module, and I honestly think the ability to optionally display token-tip info would be a great addition to this module.

**What system(s) do you want this feature to work with?**
This feature is system agnostic, although I primarily use DND5E.

**What other modules do you use that you want to ensure work well with this feature?**
A lot, all the usual suspects..  :-)  I'll hit you up on Discord and send you a list of you like.

Thanks for this great module!

**Comment by illandril** [comment]
Just putting this here for my reference later so I don't need to search for the docs again when I revisit this...
```
   * game.keybindings.register("myModule", "showNotification", {
   *   name: "My Settings Keybinding",
   *   hint: "A description of what will occur when the Keybinding is executed.",
   *   uneditable: [
   *     {
   *       key: "Digit1",
   *       modifiers: ["Control"]
   *     }
   *   ],
   *   editable: [
   *     {
   *       key: "F1"
   *     }
   *   ],
   *   onDown: () => { ui.notifications.info("Pressed!") },
   *   onUp: () => {},
   *   restricted: true,                         // Restrict this Keybinding to gamemaster only?
   *   reservedModifiers: ["Alt""],              // If the ALT modifier is pressed, the notification is permanent instead of temporary
   *   precedence: CONST.KEYBINDING_PRECEDENCE.NORMAL
   * }
```
