### ISSUE TITLE
Tooltips do not display on certain characters

### ISSUE THREAD

**Issue by Squiggakun** [illandril/FoundryVTT-token-tooltips#63]
Exactly 3 of the 4 player characters will not display tooltips.  Cloning the characters, exporting and reimporting the data over new sheets, and fiddling with the display settings failed to resolve this.  No other tokens, monster or npc, are impacted as far as I could tell.

**What steps did you take before experiencing the problem?**
Updating from foundry v9 to v10, and presumable tooltips v2.11.1 to 3.0.0

**Foundry Versions**
 - Version of this module: 3.0.0
 - Foundry Version: 10 build 284
 - System Name and Version: PF2e 4.0.0-beta 3
 - Browser Name and Version: Foundry Client, but also on players end in at least chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
All other modules were disabled and this issue persists.

Character data is included.  Of the 4 characters provided, only Garfish is unaffected.
[Character data.zip](https://github.com/illandril/FoundryVTT-token-tooltips/files/9530393/Character.data.zip)

**Comment by illandril** [comment]
It looks like it might be because of a change in how PF2e handles spellcasting data. Try setting "Permission to Show" to "Hide from Everyone" for the "Spell Slots" Standard Tooltip Value - this should get the rest of the tooltip showing at least until I am able to fix this.
