### ISSUE TITLE
Comparing the distance between 2 characters; Show HP as Hearts

### ISSUE THREAD

**Issue by medeiros961030** [illandril/FoundryVTT-token-tooltips#64]
Hello, I currently use the tooltip token (another module that works similar to yours) but I would like to migrate it, but there are 2 features of it that yours does not have, and I believe it would be a great addition:

1° - Show the distance between the token that you are currently controlling and the token that you are with the mouse over

2° - The module I use also indicated player health through hearts. Unfortunately yours doesn't have this or similar feature.

(GM vision) ![image](https://user-images.githubusercontent.com/112792783/189217541-d18112b8-3f71-4fa8-9fe4-f9caebeafa80.png)

(player vision) 
![image](https://user-images.githubusercontent.com/112792783/189220855-e8c7f8a9-013c-48f9-872d-4331025e6d45.png)

**Comment by illandril** [comment]
Can you elaborate on what you want for "indicated player health through hearts"?
I don't necessarily need to know what the other module did, just what your ideal solution would look like, and what minimal features you'd need to be able to switch in case I don't have time to implement your ideal solution.

Does the HP as Hearts apply just to "Hostile"? To "Hostile" and "Neutral"? To NPCs? To anyone except the current player's characters? To every token, including the character's own tokens?
How does HP translate to hearts? Is it X HP = 1 heart? Everybody has X hearts at max HP, with hearts shown proportional to HP percentage (ex. 0% = 0 hearts, 0.1-25% = 1 heart, 25.1-50% = 2 hearts, 50.1-75% = 3 hearts, 75.1-100% = 4 hearts)?

**Comment by medeiros961030** [comment]
Clear. I'll base my description on his module, but it would basically be the same as those old RPG's. there would be 4 hearts. when someone loses a certain power of life, that heart goes dark or disappears.
4 Hearts -100% to 75%
3 Hearts - 74% to 50%
2 hearts - 25% to 49%
1 heart - 1% to 24%

Hearts must appear to ALL but ONLY hearts. So it is possible for any player to know the life condition of any person, but don't get the percentage details of this life, whether friendly or hostile.

**Comment by illandril** [comment]
If someone has more than 100% HP (ex. temporary hit points in D&D 5e), should they still show 4 hearts, show a 5th heart, or do you have no preference because you never get into that situation in your games?

**Comment by medeiros961030** [comment]
I think it's best not to show any additional hearts. I use this module to break much of the player's "metagame". With it, they cannot see the specific health of an enemy, nor an ally. I believe that temporary life has no need to be shown

As for the distance between the main character and who he is placing the mouse on, do you find it too complicated to implement?

**Comment by illandril** [comment]
I haven't looked into how much work either feature would take yet - conceptually it seems simple enough, but I haven't looked into distance measurement lookups in Foundry yet so I don't know yet if there will be any barriers to implement it or not.

**Comment by medeiros961030** [comment]
No problem, I look forward to seeing you if you get any improvements. I say this because the other module I use probably won't update to V10, so everyone will migrate to yours

Thank you again!

**Comment by illandril** [comment]
I've uncovered an edge case for showing the distance between two tokens: tokens that take up multiple spaces.

Would you prefer the distance value to be "distance to reach" or "distance to center"?

Example "distance to reach" values...
![Screenshot from 2022-09-14 15-27-36](https://user-images.githubusercontent.com/469205/190245368-f0122112-260a-438e-aa8b-39c491b452fa.png)
![Screenshot from 2022-09-14 15-29-15](https://user-images.githubusercontent.com/469205/190245363-12950761-f947-4693-badf-e802d8bd32c0.png)

Example "distance to center" values...
![Screenshot from 2022-09-14 15-27-16](https://user-images.githubusercontent.com/469205/190245366-7409167f-7424-406e-a376-d0001f9e1fef.png)
![Screenshot from 2022-09-14 15-28-56](https://user-images.githubusercontent.com/469205/190245359-93720edf-4eee-496f-816d-91ade7d49605.png)

**Comment by illandril** [comment]
And one more question re: hearts... are you OK with this instead?
4 Hearts -100% to 76%
3 Hearts - 75% to 51%
2 hearts - 50% to 26%
1 heart - 25% to 1%
0 heart = 0%

**Comment by medeiros961030** [comment]
About hearts:  It's perfect!!

Abort distance: I prefer the  distance to reach. Normally the players use that distance to calculate an attack or spell, instead of put the mouse over his token and calculating manual to their target
