### ISSUE TITLE
Tooltip background only one column wide

### ISSUE THREAD

**Issue by JacksonBockus** [illandril/FoundryVTT-token-tooltips#65]
![image](https://user-images.githubusercontent.com/4021766/190927028-c7e25797-83e5-4d88-ae49-435950e07c08.png)

Notes: Tried in Chrome and Firefox, and with all modules other than token tooltips disabled. Please reach out if you need more information.

**Comment by illandril** [comment]
What version of Foundry?
What System (including version)?
What version of Illandril's Token Tooltips?
What other modules do you have enabled?
What version of Chrome/Firefox?

**Comment by JacksonBockus** [comment]
Foundry version is 10.285, system is dnd5e 2.0.2, ITT 3.0.1, issue persists when all other modules are disabled. Firefox 104.0.2 64bChrome 105.0.5195.125 x86_64On Sep 19, 2022, at 9:13 AM, Joe Spandrusyszyn ***@***.***> wrote:﻿
What version of Foundry?
What System (including version)?
What version of Illandril's Token Tooltips?
What other modules do you have enabled?
What version of Chrome/Firefox?

**Comment by illandril** [comment]
I have reproduced the issue. This happens if and only if Spell Slots is enabled and nothing would show for the token after Spell Slots.

As a temporary workaround until I fix this, either turn off "Spell Slots" display or add any custom tooltip value that will show for all tokens.

**Comment by JacksonBockus** [comment]
Thanks for the workaround; can confirm it works.

**Comment by oestred** [comment]
Following, did temp workaround for now. thank you!

**Comment by ElvenChaos** [comment]
The "resources" option is affected by the same bug too, and the same workaround works for it as well.

**Comment by oestred** [comment]
Thanks for fixing the issue! This module is a great one that I use all the time so your efforts with it are appreciated. It is so helpful to be able to see ac or hp or whatever quickly without having to open char or npc sheets.
