### ISSUE TITLE
dnd5e 2.1.x error

### ISSUE THREAD

**Issue by MaxPat931** [illandril/FoundryVTT-token-tooltips#72]
After updating to dnd5e 2.1.x the tooltip no longer shows on hover, see error below

**Screenshots**
![image](https://user-images.githubusercontent.com/86370342/212459677-e9dce95a-570b-439e-b579-b2e391ebdfd8.png)

**Foundry Versions**
 - Version of this module: 3.1.1
 - Foundry Version: 10.291
 - System Name and Version: dnd5e 2.1.x
 - Browser Name and Version: Chrome

**Comment by illandril** [comment]
Try turning off Dmg Res/Vuln and/or Cond Imm for now as a work around.
