### ISSUE TITLE
Support for Level Up Advanced 5E system

### ISSUE THREAD

**Issue by PsykotikDragon** [illandril/FoundryVTT-token-tooltips#76]
**Describe the solution you'd like**
Would it be possible to include a setup of defaults for A5E? the overall features of 5e would work for most of it, with only a few additional items, but they're labeled diff as it's a diff system from 5e similar to how pf1/pf2 have similar items to 3e/3.5e but most likely have different names in foundry for ea stat, save, check, skill, etc

**What system(s) do you want this feature to work with?**
Level Up: Advanced 5th Edition (A5E)

**What other modules do you use that you want to ensure work well with this feature?**
I'm sure there's plenty of them out there that'd go nicely w/ this but off the top of my head I can't think of any...just getting this to work in the system proper would be nice enough for starters.

**Additional context**
Here's the [token debug txt](https://github.com/illandril/FoundryVTT-token-tooltips/files/10791690/message.txt) file for the a5e tokens if that helps any. I just dragged & copied the debug popup for all the stats on it.

**Comment by illandril** [comment]
I don't use the A5E system, so it's possible I missed some things - if you notice anything missing that you think should be supported, or if any values are showing incorrectly, feel free to open another issue with details on what's missing/wrong.
