### ISSUE TITLE
Add an export/import option to transfer settings between worlds

### ISSUE THREAD

**Issue by PsykotikDragon** [illandril/FoundryVTT-token-tooltips#77]
**Is your feature request related to a problem? Please describe.**
not exactly a problem, most of the default standard stuff pretty much works as-is but would like to change icons for them or even remove the ones that don't apply to clean up my interface when I need to open it up for my system.

**Describe the solution you'd like**
being able to edit/rearrange/remove or select the defaults for the 'standard values' for the system you're using would be awesome...maybe allowing an export/import or save feature.

**What system(s) do you want this feature to work with?**
A5E specifically would be great, but I think this requested feature is/would be system-agnostic

**Comment by illandril** [comment]
You can remove the ones you don't want to use by setting "Permission to Show" to "Hide from Everyone" for the options you don't want to use.

Re-arranging the options is covered by #58.
