### ISSUE TITLE
Canvas 3D support

### ISSUE THREAD

**Issue by Trokkin** [illandril/FoundryVTT-token-tooltips#88]
**Describe the bug**
With Canvas 3D, the tooltip is not displayed next to token but somewhere else on the screen.
There's a [similar issue](https://github.com/mclemente/healthEstimate/issues/83) with Health Estimate, with suggestion that it is displayed by 2D camera coordinates.

Might be more of a feature request.
Maybe it is more applicable for the Canvas3D.

**What steps did you take before experiencing the problem?**
1. Open a Canvas 3D map
2. Place any token
3. Hover the token

**What did you expect to happen?**
Tooltip should display next to the token's projection on the screen from its real position on 3D scene

**What happened instead?**
Tooltip is displayed somewhere else but not next to the token

**Screenshots**
![image](https://github.com/illandril/FoundryVTT-token-tooltips/assets/33575033/dc69476a-e70e-450f-91ca-3d8f6eec6ae8)

**Foundry Versions**
 - Version of this module: 3.4.2
 - Foundry Version: 11.305
 - System Name and Version: Windows 10
 - Browser Name and Version: Chrome

**What other modules did you have active when experiencing this issue (include both names and versions)?**
- Canvas 3D 5.3.8

**Comment by illandril** [comment]
I will not be spending time adding support for a premium module I have no interest in using myself.

If someone wants to submit a PR for this, I would consider included it (as long as doing so would not jeopardize the functionality or maintainability for non-Canvas 3D users).
