### ISSUE TITLE
Use concat in the data key

### ISSUE THREAD

**Issue by extazz17** [illandril/FoundryVTT-token-tooltips#90]
**Is your feature request related to a problem? Please describe.**
I'm using a Fallout 2d20 system, i want to show the carryWeight (lbs) in this format : `[carryWeight.value] / [carryWeight.max]`
I can't use concatenation to add some string in the dataKey ("/").

I don't understand how it is possible to do math and not concat (this means that the value is executed and not bound).

**Describe the solution you'd like**
Able to use something like this => `carryWeight.value + "/" + carryWeight.max`
Note : I can use math if i use `(carryWeight.value + carryWeight.mod) + "/" + carryWeight.max`

In my Javascript knowledge, this seems pretty simple to solve.
I see you use TS in your project so  i can't do it by myself for the moment.

**Describe alternatives you've considered**
-

**What system(s) do you want this feature to work with?**
Globally

**What other modules do you use that you want to ensure work well with this feature?**
-

**Additional context**
-

**Comment by illandril** [comment]
Unless I'm overlooking something, this is far from easy (without taking advantage of a library like moo that does tokenization, which would substantially increase the size of my module).

If you can create a Javascript function that can provide all of the following results, without using a heavy-duty tokenizer, lexer, or language processing library, I can convert it into Typescript:
```
getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a & "/" & system.b') -> { value: "12 / 13" }

getMultiValue({
  system: {
    a: 10,
    b: 5,
    c: 2,
    d: 10
  },
}, 'system.a + system.b & "/" & system.c * system.d') -> { value: "15 / 20" }

getMultiValue({
  system: {
    a: 12,
    b: 'lbs',
  },
}, 'system.a & system.b') -> { value: "12lbs" }

getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a & system.b') -> { value: "1213" }
```
... in addition to everything that is already supported...
```
getMultiValue({}, '') -> null

getMultiValue({}, '10') -> { value: 10 }

getMultiValue({}, '10 + 5+7- 2') -> { value: 20 }

getMultiValue({
  system: {
    attributes: {
      stealth: {
        label: 'Stealth',
        value: 7,
        dc: 17,
        totalModifier: 7,
        rank: 3,
     },
    },
  },
}, 'system.attributes.stealth.value') -> { value: 7 }

getMultiValue({
  system: {
    attributes: {
      stealth: {
        label: 'Stealth',
        value: 7,
        dc: 17,
        totalModifier: 7,
        rank: 3,
      },
    },
  },
}, 'system.attributes.stealth.label') -> { value: 'Stealth }

getMultiValue({
  system: {
    attributes: {
      stealth: {
        value: 7,
        dc: 17,
        totalModifier: 7,
        rank: 3,
      },
    },
  },
}, 'system.attributes.stealth') -> { value: 7 }

getMultiValue({
  system: {
    attributes: {
      stealth: {
        value: 7,
        dc: 17,
        totalModifier: 7,
        rank: 3,
      },
    },
  },
}, 'system.attributes.stealth.value + 10') -> { value: 17 }

getMultiValue({
  system: {
    a: 10,
    b: 'def',
  },
}, 'system.a + system.b') -> null

getMultiValue({
  system: {
    a: 10,
    b: 'def',
  },
}, 'system.c') -> null

getMultiValue({
  system: {
    attributes: {
      hp: {
        value: 7,
        temp: 5,
        max: 10,
      },
    },
  },
}, 'system.attributes.hp.value+system.attributes.hp.temp') -> { value: 12 }


getMultiValue({
  system: {
    attributes: {
      hp: {
        value: 7,
        temp: 5,
        max: 10,
      },
    },
  },
}, 'system.attributes.hp.value+system.attributes.hp') -> { value: 7, max: 10, temp: 5 }

getMultiValue({
  system: {
    a: 3,
    b: 5,
  },
}, 'system.a * system.b') -> { value: 15 }


getMultiValue({
  system: {
    a: 20,
    b: 5,
  },
}, 'system.a / system.b') -> { value 4 }

getMultiValue({
  system: {
    a: 18,
    b: 5,
  },
}, 'system.a / system.b') -> { value: 3.6 }


getMultiValue({
  system: {
    a: 13,
    b: 10,
  },
}, 'system.a % system.b') -> { value: 3 }

getMultiValue({
  system: {
    a: 13,
    b: 12,
  },
}, 'system.a > system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a > system.b') -> null


getMultiValue({
  system: {
    a: 13,
    b: 12,
  },
}, 'system.a >= system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a >= system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 13,
    b: 14,
  },
}, 'system.a >= system.b') -> null

getMultiValue({
  system: {
    a: 13,
    b: 12,
  },
}, 'system.a == system.b') -> null

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a == system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a == system.b') -> null

getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a < system.b') -> { value: 12 }

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a < system.b') -> null

getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a <= system.b') -> { value: 12 }

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a <= system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 14,
    b: 13,
  },
}, 'system.a <= system.b') -> null


getMultiValue({
  system: {
    a: 13,
    b: 12,
  },
}, 'system.a != system.b') -> { value: 13 }

getMultiValue({
  system: {
    a: 13,
    b: 13,
  },
}, 'system.a != system.b') -> null

getMultiValue({
  system: {
    a: 12,
    b: 13,
  },
}, 'system.a != system.b') -> { value: 12 }
```

**Comment by extazz17** [comment]
I looked at your code, it seems that you take all possible cases, we notice your desire not to use `eval` or other alternatives so as not to open a breach, it would have been much simpler here but I don't know all the Foundry system guidelines on this.

I imagined this would apply "on-top" of your code.

The final result used in `updateCustomAttributeRow` would be a string.
I notice that if `typeof value.value === 'string'`, you expect it as an image, you should then check if it is an image, if not, treat it as a string.
For each element of this object, process the elements of type `number` with your `getMultiValue()`, return them as a string.
Once everything has been evaluated, simply concat the final object into a string to display on Foundry

```
const buildObject = (str) => {
	const parts = str.split('&&');
	const result = parts.map(part => {
		part = part.trim();
		if (part.startsWith('"') && part.endsWith('"')) {
			return {
				type: 'string',
				value: part.slice(1, -1)
			};
		} else {
			return {
				type: 'number',
				value: part
			};
		}
	});
	return result;
}
```
If we want to concat strings, we would just need to use the separators : 

-  `( )` for "math" parts 
- `&&` for separator in the logic
- `"` to specify a "string" part


These separators are not currently usable in keys so there is no risk of users using them.
It is simply necessary to indicate that the '&&' cannot be used in the string (reserved character)

### So here are examples of results:
```
// My initial request
buildObject('(carryWeight.value) && "/" && (carryWeight.max)');
```
**Result :** 
<img width="433" alt="image" src="https://github.com/illandril/FoundryVTT-token-tooltips/assets/55485926/ceffe2ce-82bc-4c04-9d02-0391da82ac1f">

```
// A currently used possible value
buildObject('carryWeight.value + carryWeight.mod');
```
**Result :** 
<img width="578" alt="image" src="https://github.com/illandril/FoundryVTT-token-tooltips/assets/55485926/43882221-57e6-439f-938a-d37eccbe9626">

I don't know all the impacts but this way of doing things allows you not to modify the existing code, it just adds an overlay which allows each "parameter" separated by && to be processed by its value type.
Unfortunately I cannot test this code on foundry because it is in TS and I cannot access it via the console but I tested it on my side.
