### ISSUE TITLE
An option for GM only

### ISSUE THREAD

**Issue by heyzoms** [illandril/FoundryVTT-token-tooltips#96]
**Is your feature request related to a problem? Please describe.**
My players don't like it but its very useful for me when using monsters 

**Describe the solution you'd like**
Just an option to allow for GM only or to be able to select what kind of user is allow to use it

**Describe alternatives you've considered**
N/A

**What system(s) do you want this feature to work with?**
I use pf2e but the option shouldn't interfere with any system, but idk. I'm no expert 

**What other modules do you use that you want to ensure work well with this feature?**
I use to many but it shouldn't interfere

**Additional context**
N/A

**Comment by illandril** [comment]
This should already be possible by setting "Tooltip Visibility" to "No Tokens (Show tooltips to GMs only)".

Feel free to re-open if that doesn't work for you.

**Comment by ilgaran** [comment]
@illandril 
Seems like currently the tokens are either displayed for all players or none - would it be possible to add a player setting for enabling\disabling the tooltip visibility?

**Comment by illandril** [comment]
> @illandril 
> Seems like currently the tokens are either displayed for all players or none - would it be possible to add a player setting for enabling\disabling the tooltip visibility?

You mean a setting for each individual player? Is this to support individual player preferences, where some of your players don't like the tooltips, or is there some reason why you as a GM would like to prevent some (but not all) players from being able to see the tooltips?

**Comment by ilgaran** [comment]
@illandril Thanks for the swift response! It is former: some of my players got annoyed by the tooltips, cause those take a lot of the space on their monitor. One of them even said they had performance issues because of that, but It's hard for me to verify that. 
So giving them an option to just disable a module activity on their side would really help

**Comment by ilgaran** [comment]
@illandril I tried making a solution myself, but lack the permissions to upload it. If that may help, I would be glad to share what I came up with

**Comment by illandril** [comment]
Split off into #114
