### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by SpectreWulf** [illandril/FoundryVTT-token-tooltips#97]
**Is your feature request related to a problem? Please describe.**
Is there are any future plans to add a "dark theme" version of the Tooltip along with assigning individual colours to the icons ?

**Describe the solution you'd like**
An option to switch between existing colour scheme and a dark theme version with darker backgrounds. Also a colour picker for the fontawesome icons.

**Describe alternatives you've considered**
Currently Token Tooltip Alt has a nice dark theme.

**What system(s) do you want this feature to work with?**
Theme is pretty system agnostic. I would love support for 13th Age system.

**What other modules do you use that you want to ensure work well with this feature?**
None.

**Additional context**
None.

**Comment by illandril** [comment]
I have split this into two separate features:
1. #97
2. #98

**Comment by illandril** [comment]
If you don't like any of the colors I picked for Dark Mode, just let me know what colors you would like changed to what.

As long as they have sufficient contrast for accessibility, I don't mind changing them.

**Comment by SpectreWulf** [comment]
> If you don't like any of the colors I picked for Dark Mode, just let me know what colors you would like changed to what.
> 
> As long as they have sufficient contrast for accessibility, I don't mind changing them.

Wow I wasn't expecting such a quick response and update! :D 

Thanks the Dark theme looks absolutely amazing! <3 <3
