### ISSUE TITLE
Tidy5eSheet Compatability Issue

### ISSUE THREAD

**Issue by Sayshal** [illandril/FoundryVTT-token-tooltips#99]
**Describe the bug**
When using Tidy5e and this module. Opening the character sheet that results in displaying the Tidy5e Character sheet results in this error.

**What steps did you take before experiencing the problem?**
1. Load scene.
2. Open actor via double clicking token on scene OR from sidebar.
3. Error in console and sluggishness opening character sheet.

**What did you expect to happen?**
Sheet to open without laggy and no error.

**What happened instead?**
Direct lag as a result of this error (without this Token Tooltips the lag is not present).

**Screenshots**
https://i.imgur.com/0nkOPOz.png

**Foundry Versions**
 - Version of this module: 3.10.3 (Tidy 5e 3.7.0)
 - Foundry Version: 11.315
 - System Name and Version: D&D5e 3.1.2
 - Browser Name and Version: Electron App (provided by theripper via https://github.com/theripper93/fvtt-player-client/releases/tag/1.5.4

**What other modules did you have active when experiencing this issue (include both names and versions)?**
https://i.imgur.com/HKpnJxt.png

**Comment by illandril** [comment]
I cannot reproduce any lag or any behavior that could explain lag on even the worst computer. The only things that happen from this module when this error happens is basically the log message.

All that happens in this module when the Actor Sheet renders, it looks for the inventory and features tabs. If it can't find them, it logs this error and stops.

To stop Token Tooltips from even doing that much, set the "Item Uses" Standard Tooltip Value's "Permission to Show" to "Hide from Everyone".

If you can still reproduce the issue after upgrading to Foundry v12 and Token Tooltips 4.0.0 (or whatever the latest is at the time you upgrade your Foundry), provide the names and version numbers of all modules you're using, and export the data for at least one of the characters that exhibit this problem, and I can investigate further.
